#!/usr/bin/env bash
#
# ##########
# JULIETFLOW
# ##########
#
# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail

function echoHelp() {
    echo "USAGE: julietflow -i movie.ccs.bam -r reference.fasta

  -i [arg]  BAM CCS file to process. Required.
  -r [arg]  Reference FASTA file. Required.
  -c [arg]  Juliet target config. Default='<HIV>'
  -j [arg]  Number of CPU cores. Default=1
  -m [arg]  Maximal number of re-align iterations. Default=1
  -t [arg]  Target reference FASTA, per default using --ref.
  -k        Keep temporary files
  -h --help This help page"
  exit 0
}

# Option parsing
config='<HIV>'
cores=1
max=1
keep="0"
helpRequested="0"

if [[ $# -eq 0 ]]; then
    echoHelp
fi

PROGNAME=${0##*/}
SHORTOPTS="hmi:r:c:j:t:m:"
LONGOPTS="help"

ARGS=$(getopt -s bash --options $SHORTOPTS  \
  --longoptions $LONGOPTS --name $PROGNAME -- "$@" )

eval set -- "$ARGS"

while [[ $# -gt 0 ]] ; do
   case $1 in
    -i)
      shift
      if [[ ${1} == /* ]]; then input=${1}; else input=$(pwd)/${1}; fi;;
    -r)
      shift
      if [[ ${1} == /* ]]; then reference=${1}; else reference=$(pwd)/${1}; fi;;
    -c)
      shift
      config=$1;;
    -j)
      shift
      cores=$1;;
    -t)
      shift
      target=$1;;
    -m)
      shift
      max=$1;;
    -k)
      keep="1";;
    -h | --help)
      helpRequested="1";;
    \?)
      echo "Invalid option: -$1" >&2;;
  esac
  shift
done

if [[ "${helpRequested}" = "1" ]]; then
  echoHelp
fi

if [[ -z "${input:-}" ]]; then
    echo "Please provide the CCS BAM file via -i"
    exit 1
fi

if [[ -z "${reference:-}" ]]; then
    echo "Please provide the reference FASTA file via -r"
    exit 1
fi

if [[ -z "${target:-}" ]]; then
  target=$reference
fi

# Get directory of the input file, file prefix and suffix
run_directory=${input%/*}
run_name=${input##*/}
run_suffix=${run_name##*.}
run_prefix=${run_name%.*}

# Main script
wdir=$(pwd)
if [[ "${keep}" = "1" ]]; then
  if [[ -d ${wdir}/tmp ]]; then
    echo "Directory ${wdir}/tmp already exists, please remove to use option -k"
    exit 1
  fi
fi

function align()
{
    blasr ${input} $1 --placeGapConsistently --bam --out out.bam --nproc ${cores} --scoreMatrix "-1 4 4 4 6 4 -1 4 4 6 4 4 -1 4 6 4 4 4 -1 6 6 6 6 6 6" --maxMatch 15
    samtools sort -@${cores} -o ${run_prefix}.align.bam out.bam
    samtools index ${run_prefix}.align.bam
    rm out.bam
}

# Create provided directory tree and cd
function mmkdir()
{
    mkdir -p $1;
    cd $1
}

# Create temporary directory, under which all work will be performed
tdir=$(mktemp -d) && cd ${tdir}

# Generally, never do work if file is already present.
# Align against given reference and create consensus sequence
mmkdir 0
if [ ! -f ${run_prefix}.align.bam ]; then align ${reference}; fi
if [ ! -f ${run_prefix}.cons ]; then cp ${reference} ${run_prefix}.cons; fi
cd ..

# Iteratively align against previous consensus
for i in $(seq 1 ${max}); do
    mmkdir ${i}
    if [ ! -f ${run_prefix}.cons ]; then fuse ../$(($i-1))/${run_prefix}.align.bam; fi
    if [ ! -f ${run_prefix}.align.bam ]; then align ${run_prefix}.cons; fi
    cd ..
done

# Re-map last alignment against original reference
mmkdir merge
cleric ../${max}/${run_prefix}.align.bam ../${max}/${run_prefix}.cons $target
juliet ${run_prefix}_cleric.bam -c ${config}
cp ${run_prefix}_cleric.html ${wdir}/

if [[ "${keep}" = "1" ]]; then
  mkdir ${wdir}/tmp
  cd ..
  cp -R * ${wdir}/tmp/
fi

# switch back to original root
cd ${wdir}
rm -rf ${tdir}